### ISSUE TITLE
Create and Document ToolbarLogo and Theme Switcher UI Components for Reusable and Consistent Implementation

### ISSUE THREAD

**Issue by esmaeil-ahmadipour** [pactus-project/pactus-gui#35]
## Overview
**Component/Feature:** Reusable UI components  
**Reason:** Current UI components are not reusable or aligned with the Figma design. A refactor is needed for consistency and maintainability.

## Goals
- Identify and create reusable UI components from the Figma design.  
- Align with Material 3 design specifications.  
- Improve maintainability by consolidating UI elements into reusable components.

## Proposed Changes
- Review the Figma design to identify reusable UI components (e.g., ToolbarLogo, Theme Switcher).
- For each reusable component identified, create a separate issue with detailed implementation steps.  
- Document parameters and Material 3 specs for each component.  
- Develop Flutter widgets for reusability and replace hardcoded UI elements with reusable components.

## Design Reference
- **Figma Design:** [Link to Figma Design](https://www.figma.com/design/o4xKRt7MeSuyjIMOxU1U5v/Pactus-Applications-(Community)?node-id=0-1&node-type=canvas&t=axM2jYbzZYXJdXmK-0)

## Related Issues
- [issue #25](https://github.com/pactus-project/pactus-gui/issues/25): Implement Theme Management.
- [issue #34](https://github.com/pactus-project/pactus-gui/issues/34): Refactor and align text styles in themes with Figma design specifications.

----

## Tasks:

  - [x] Task 1:  Create `ToolbarLogo` UI : [Link 1](https://github.com/user-attachments/assets/35391867-b3a8-4a4e-ac0a-a8d0ed6b1809) / [Link 2](https://github.com/user-attachments/assets/37a3d345-1c39-4a6b-b0eb-f4737d0a5023) 
  - [x] Task 2:  Write tests, and docs for `ToolbarLogo`  
  - [x] Task 3:   Write docs for `ToolbarLogo`  
  - [x] Task 4:  Create `theme switcher`  UI, tests, and docs :    [Link 1](https://github.com/user-attachments/assets/d735597d-ce00-46b0-983b-2e942f305b38)  / [Link 2](https://github.com/user-attachments/assets/baad29e9-5375-44ff-b2f1-a5144ffe81db)
  - [x] Task 5:  Write tests, and docs for `theme switcher`  
  - [x] Task 6:  Write docs for `theme switcher`

**Comment by esmaeil-ahmadipour** [comment]
### Problem :
According material button spec , this dimensions is wrong and out of spec.
spec reference url : https://m3.material.io/components/buttons/specs#0697c92a-54ba-4921-b28a-0f4abeea0a85

![Screenshot from 2024-12-05 10-55-58](https://github.com/user-attachments/assets/fb4ed332-0843-4a2c-9dd4-37e7a2abae5b)

and cant develop another styles of button according figma.
spec reference url : https://m3.material.io/components/buttons/specs#36956f5c-af6f-491a-99e8-2fa72d8d2d0c

### Solutions:
1-  the designer should update the design to align with the standard specifications of Material Design. This ensures consistency and a better user experience

2- we can implement a custom design without strictly adhering to Figma's design for now. This approach allows us to move forward and refactor later to align with the finalized design. 

---

@Ja7ad

**Comment by esmaeil-ahmadipour** [comment]
One problem that needs to be fixed is the inconsistency between the light theme and dark theme in the Figma design. These differences should be addressed to ensure uniformity across both themes.

<details>
<summary>Example item 1 </summary>

![option_list_001](https://github.com/user-attachments/assets/d7cb34f3-d1c7-4fa6-823d-0f7b25261516)

![option_list_002](https://github.com/user-attachments/assets/3b5bd803-b869-427d-9c92-c06ae6655617)
</details>


<details>
<summary>Example item 2 </summary>

![options list1](https://github.com/user-attachments/assets/af003ff9-1cdf-46e1-8d05-ed96f90be963)


![options list2](https://github.com/user-attachments/assets/c8306b37-f428-455c-ae52-cb727e1c8df3)
</details>


---

@Ja7ad

**Comment by esmaeil-ahmadipour** [comment]
List of Component need create in this issue:

<details>
<summary>1 - theme switcher</summary>

<img src="https://github.com/user-attachments/assets/d735597d-ce00-46b0-983b-2e942f305b38" alt="theme_switcher1"   height="50">

  <img src="https://github.com/user-attachments/assets/baad29e9-5375-44ff-b2f1-a5144ffe81db" alt="theme_switcher2"   height="50">

</details>

----

<details>
<summary>2- small logo with dynamic color</summary>

<img src="https://github.com/user-attachments/assets/35391867-b3a8-4a4e-ac0a-a8d0ed6b1809" alt="logo_widget1"   height="50">

<img src="https://github.com/user-attachments/assets/37a3d345-1c39-4a6b-b0eb-f4737d0a5023" alt="logo_widget2"   height="50">

</details>

---

**Comment by esmaeil-ahmadipour** [comment]
Tasks :

- [ ]  1 - theme switcher :   [Link 1](https://github.com/user-attachments/assets/d735597d-ce00-46b0-983b-2e942f305b38)  / [Link 2](https://github.com/user-attachments/assets/baad29e9-5375-44ff-b2f1-a5144ffe81db)
- [ ]  2 - small logo with dynamic color : [Link 1](https://github.com/user-attachments/assets/35391867-b3a8-4a4e-ac0a-a8d0ed6b1809) / [Link 2](https://github.com/user-attachments/assets/37a3d345-1c39-4a6b-b0eb-f4737d0a5023)
